# Generated by Django 5.2.3 on 2025-11-15 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Users",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64)),
                ("user_name", models.CharField(max_length=64)),
                ("email", models.CharField()),
                ("password", models.CharField()),
            ],
        ),
    ]
