# Generated by Django 5.2.3 on 2025-11-15 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Users",
        ),
    ]
